package ecode

var zhCNText = map[int]string{
	Success:       "成功",
	Failed:        "系统错误",
	CaptchaFailed: "验证码获取失败",
	ParamsFailed:  "参数校验错误",
	TokenFailed:   "token无效",
	LoginFailed:   "登录失败",

	CasbinFailed:              "权限不足",
	RegisterFailed:            "注册失败",
	CaptchaVerifyFailed:       "验证码校验失败",
	MenuListFailed:            "获取路由菜单失败",
	CasbinAddFailed:           "权限添加失败",
	CasbinDelFailed:           "权限删除失败",
	CasbinUpdateFailed:        "权限更新失败",
	CasbinListFailed:          "权限列表失败",
	RateLimitAllowFailed:      "超出请求频率限制",
	FileWithExcelFailed:       "不是excel文件",
	FileReportFailed:          "文件上传失败",
	FileOpenFailed:            "文件打开失败",
	GetUserInfoFailed:         "获取用户信息失败",
	UpdateUserInfoFailed:      "更新用户信息失败",
	GetCasbinListFailed:       "获取权限表信息失败",
	NotAdminID:                "无权限操作该接口",
	SetCasbinFailed:           "更新权限失败",
	GetDictListFailed:         "获取字典序失败",
	GetSettingsFailed:         "获取layout配置失败",
	UpdateSettingsFailed:      "设置layout配置失败",
	TokenValidateFailed:       "token解析失败",
	UpdatePasswordFailed:      "更新用户密码失败",
	RateLimitAllowErrFailed:   "请求频率限制接口报错",
	DebugPerfFailed:           "性能测试失败",
	WebSocketCreateConnFailed: "创建websocket连接失败",
	ParamsAnalysisFailed:      "参数解析异常",
	SameDataSaveFailed:        "已存在相同数据，保存失败",
}
