// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Global        *Global                `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetGlobal() *Global {
	if x != nil {
		return x.Global
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type Global struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyUrl      string                 `protobuf:"bytes,1,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
	ProxyJsonUrl  *Global_ProxyJsonUrl   `protobuf:"bytes,2,opt,name=proxyJsonUrl,proto3" json:"proxyJsonUrl,omitempty"`
	Lcu           *Global_LCU            `protobuf:"bytes,3,opt,name=lcu,proto3" json:"lcu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global) Reset() {
	*x = Global{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Global) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *Global) GetProxyJsonUrl() *Global_ProxyJsonUrl {
	if x != nil {
		return x.ProxyJsonUrl
	}
	return nil
}

func (x *Global) GetLcu() *Global_LCU {
	if x != nil {
		return x.Lcu
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Global_ProxyJsonUrl struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemJson        string                 `protobuf:"bytes,1,opt,name=item_json,json=itemJson,proto3" json:"item_json,omitempty"`
	SpellJson       string                 `protobuf:"bytes,2,opt,name=spell_json,json=spellJson,proto3" json:"spell_json,omitempty"`
	ChampJson       string                 `protobuf:"bytes,3,opt,name=champ_json,json=champJson,proto3" json:"champ_json,omitempty"`
	ProfileIconJson string                 `protobuf:"bytes,4,opt,name=profile_icon_json,json=profileIconJson,proto3" json:"profile_icon_json,omitempty"`
	MapIconJson     string                 `protobuf:"bytes,5,opt,name=map_icon_json,json=mapIconJson,proto3" json:"map_icon_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Global_ProxyJsonUrl) Reset() {
	*x = Global_ProxyJsonUrl{}
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_ProxyJsonUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_ProxyJsonUrl) ProtoMessage() {}

func (x *Global_ProxyJsonUrl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_ProxyJsonUrl.ProtoReflect.Descriptor instead.
func (*Global_ProxyJsonUrl) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Global_ProxyJsonUrl) GetItemJson() string {
	if x != nil {
		return x.ItemJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetSpellJson() string {
	if x != nil {
		return x.SpellJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetChampJson() string {
	if x != nil {
		return x.ChampJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetProfileIconJson() string {
	if x != nil {
		return x.ProfileIconJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetMapIconJson() string {
	if x != nil {
		return x.MapIconJson
	}
	return ""
}

type Global_LCU struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 游戏流程相关
	GameflowPath        string `protobuf:"bytes,2,opt,name=gameflow_path,json=gameflowPath,proto3" json:"gameflow_path,omitempty"`
	GameflowSessionPath string `protobuf:"bytes,3,opt,name=gameflow_session_path,json=gameflowSessionPath,proto3" json:"gameflow_session_path,omitempty"`
	ReconnectPath       string `protobuf:"bytes,4,opt,name=reconnect_path,json=reconnectPath,proto3" json:"reconnect_path,omitempty"`
	// 召唤师相关
	SummonerPath        string `protobuf:"bytes,5,opt,name=summoner_path,json=summonerPath,proto3" json:"summoner_path,omitempty"`
	SummonerByNamePath  string `protobuf:"bytes,6,opt,name=summoner_by_name_path,json=summonerByNamePath,proto3" json:"summoner_by_name_path,omitempty"`
	SummonerPuuidPath   string `protobuf:"bytes,7,opt,name=summoner_puuid_path,json=summonerPuuidPath,proto3" json:"summoner_puuid_path,omitempty"`
	SummonerByIdPath    string `protobuf:"bytes,8,opt,name=summoner_by_id_path,json=summonerByIdPath,proto3" json:"summoner_by_id_path,omitempty"`
	SummonerProfilePath string `protobuf:"bytes,9,opt,name=summoner_profile_path,json=summonerProfilePath,proto3" json:"summoner_profile_path,omitempty"`
	SummonerIconPath    string `protobuf:"bytes,10,opt,name=summoner_icon_path,json=summonerIconPath,proto3" json:"summoner_icon_path,omitempty"`
	// 排位相关
	RankedStatsPath string `protobuf:"bytes,11,opt,name=ranked_stats_path,json=rankedStatsPath,proto3" json:"ranked_stats_path,omitempty"`
	// 匹配相关
	MatchmakingPath string `protobuf:"bytes,12,opt,name=matchmaking_path,json=matchmakingPath,proto3" json:"matchmaking_path,omitempty"`
	ReadyCheckPath  string `protobuf:"bytes,13,opt,name=ready_check_path,json=readyCheckPath,proto3" json:"ready_check_path,omitempty"`
	// 英雄选择相关
	ChampSelectSessionPath      string `protobuf:"bytes,14,opt,name=champ_select_session_path,json=champSelectSessionPath,proto3" json:"champ_select_session_path,omitempty"`
	ChampSelectActionsPath      string `protobuf:"bytes,15,opt,name=champ_select_actions_path,json=champSelectActionsPath,proto3" json:"champ_select_actions_path,omitempty"`
	ChampSelectTradesPath       string `protobuf:"bytes,16,opt,name=champ_select_trades_path,json=champSelectTradesPath,proto3" json:"champ_select_trades_path,omitempty"`
	ChampSelectSwapsPath        string `protobuf:"bytes,17,opt,name=champ_select_swaps_path,json=champSelectSwapsPath,proto3" json:"champ_select_swaps_path,omitempty"`
	ChampSelectBenchSwapPath    string `protobuf:"bytes,18,opt,name=champ_select_bench_swap_path,json=champSelectBenchSwapPath,proto3" json:"champ_select_bench_swap_path,omitempty"`
	ChampSelectMySelectionPath  string `protobuf:"bytes,19,opt,name=champ_select_my_selection_path,json=champSelectMySelectionPath,proto3" json:"champ_select_my_selection_path,omitempty"`
	ChampSelectSkinCarouselPath string `protobuf:"bytes,20,opt,name=champ_select_skin_carousel_path,json=champSelectSkinCarouselPath,proto3" json:"champ_select_skin_carousel_path,omitempty"`
	CurrentChampionPath         string `protobuf:"bytes,21,opt,name=current_champion_path,json=currentChampionPath,proto3" json:"current_champion_path,omitempty"`
	// 符文相关
	PerksCurrentPagePath string `protobuf:"bytes,22,opt,name=perks_current_page_path,json=perksCurrentPagePath,proto3" json:"perks_current_page_path,omitempty"`
	PerksPagesPath       string `protobuf:"bytes,23,opt,name=perks_pages_path,json=perksPagesPath,proto3" json:"perks_pages_path,omitempty"`
	// 对局历史相关
	MatchHistoryPath string `protobuf:"bytes,24,opt,name=match_history_path,json=matchHistoryPath,proto3" json:"match_history_path,omitempty"`
	GameDetailPath   string `protobuf:"bytes,25,opt,name=game_detail_path,json=gameDetailPath,proto3" json:"game_detail_path,omitempty"`
	// 聊天相关
	ChatMePath string `protobuf:"bytes,26,opt,name=chat_me_path,json=chatMePath,proto3" json:"chat_me_path,omitempty"`
	// 个性化相关
	RegaliaPath               string `protobuf:"bytes,27,opt,name=regalia_path,json=regaliaPath,proto3" json:"regalia_path,omitempty"`
	ChallengesPreferencesPath string `protobuf:"bytes,28,opt,name=challenges_preferences_path,json=challengesPreferencesPath,proto3" json:"challenges_preferences_path,omitempty"`
	// 大厅相关
	LobbyPath string `protobuf:"bytes,29,opt,name=lobby_path,json=lobbyPath,proto3" json:"lobby_path,omitempty"`
	// 观战相关
	SpectateLaunchPath string `protobuf:"bytes,30,opt,name=spectate_launch_path,json=spectateLaunchPath,proto3" json:"spectate_launch_path,omitempty"`
	// 资源相关
	InstallDirPath string `protobuf:"bytes,31,opt,name=install_dir_path,json=installDirPath,proto3" json:"install_dir_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Global_LCU) Reset() {
	*x = Global_LCU{}
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_LCU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_LCU) ProtoMessage() {}

func (x *Global_LCU) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_LCU.ProtoReflect.Descriptor instead.
func (*Global_LCU) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Global_LCU) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Global_LCU) GetGameflowPath() string {
	if x != nil {
		return x.GameflowPath
	}
	return ""
}

func (x *Global_LCU) GetGameflowSessionPath() string {
	if x != nil {
		return x.GameflowSessionPath
	}
	return ""
}

func (x *Global_LCU) GetReconnectPath() string {
	if x != nil {
		return x.ReconnectPath
	}
	return ""
}

func (x *Global_LCU) GetSummonerPath() string {
	if x != nil {
		return x.SummonerPath
	}
	return ""
}

func (x *Global_LCU) GetSummonerByNamePath() string {
	if x != nil {
		return x.SummonerByNamePath
	}
	return ""
}

func (x *Global_LCU) GetSummonerPuuidPath() string {
	if x != nil {
		return x.SummonerPuuidPath
	}
	return ""
}

func (x *Global_LCU) GetSummonerByIdPath() string {
	if x != nil {
		return x.SummonerByIdPath
	}
	return ""
}

func (x *Global_LCU) GetSummonerProfilePath() string {
	if x != nil {
		return x.SummonerProfilePath
	}
	return ""
}

func (x *Global_LCU) GetSummonerIconPath() string {
	if x != nil {
		return x.SummonerIconPath
	}
	return ""
}

func (x *Global_LCU) GetRankedStatsPath() string {
	if x != nil {
		return x.RankedStatsPath
	}
	return ""
}

func (x *Global_LCU) GetMatchmakingPath() string {
	if x != nil {
		return x.MatchmakingPath
	}
	return ""
}

func (x *Global_LCU) GetReadyCheckPath() string {
	if x != nil {
		return x.ReadyCheckPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectSessionPath() string {
	if x != nil {
		return x.ChampSelectSessionPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectActionsPath() string {
	if x != nil {
		return x.ChampSelectActionsPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectTradesPath() string {
	if x != nil {
		return x.ChampSelectTradesPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectSwapsPath() string {
	if x != nil {
		return x.ChampSelectSwapsPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectBenchSwapPath() string {
	if x != nil {
		return x.ChampSelectBenchSwapPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectMySelectionPath() string {
	if x != nil {
		return x.ChampSelectMySelectionPath
	}
	return ""
}

func (x *Global_LCU) GetChampSelectSkinCarouselPath() string {
	if x != nil {
		return x.ChampSelectSkinCarouselPath
	}
	return ""
}

func (x *Global_LCU) GetCurrentChampionPath() string {
	if x != nil {
		return x.CurrentChampionPath
	}
	return ""
}

func (x *Global_LCU) GetPerksCurrentPagePath() string {
	if x != nil {
		return x.PerksCurrentPagePath
	}
	return ""
}

func (x *Global_LCU) GetPerksPagesPath() string {
	if x != nil {
		return x.PerksPagesPath
	}
	return ""
}

func (x *Global_LCU) GetMatchHistoryPath() string {
	if x != nil {
		return x.MatchHistoryPath
	}
	return ""
}

func (x *Global_LCU) GetGameDetailPath() string {
	if x != nil {
		return x.GameDetailPath
	}
	return ""
}

func (x *Global_LCU) GetChatMePath() string {
	if x != nil {
		return x.ChatMePath
	}
	return ""
}

func (x *Global_LCU) GetRegaliaPath() string {
	if x != nil {
		return x.RegaliaPath
	}
	return ""
}

func (x *Global_LCU) GetChallengesPreferencesPath() string {
	if x != nil {
		return x.ChallengesPreferencesPath
	}
	return ""
}

func (x *Global_LCU) GetLobbyPath() string {
	if x != nil {
		return x.LobbyPath
	}
	return ""
}

func (x *Global_LCU) GetSpectateLaunchPath() string {
	if x != nil {
		return x.SpectateLaunchPath
	}
	return ""
}

func (x *Global_LCU) GetInstallDirPath() string {
	if x != nil {
		return x.InstallDirPath
	}
	return ""
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\x89\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12*\n" +
	"\x06global\x18\x03 \x01(\v2\x12.kratos.api.GlobalR\x06global\"\xa0\x01\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x8f\x01\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x1aP\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"\xa9\x0e\n" +
	"\x06Global\x12\x1a\n" +
	"\bproxyUrl\x18\x01 \x01(\tR\bproxyUrl\x12C\n" +
	"\fproxyJsonUrl\x18\x02 \x01(\v2\x1f.kratos.api.Global.ProxyJsonUrlR\fproxyJsonUrl\x12(\n" +
	"\x03lcu\x18\x03 \x01(\v2\x16.kratos.api.Global.LCUR\x03lcu\x1a\xb9\x01\n" +
	"\fProxyJsonUrl\x12\x1b\n" +
	"\titem_json\x18\x01 \x01(\tR\bitemJson\x12\x1d\n" +
	"\n" +
	"spell_json\x18\x02 \x01(\tR\tspellJson\x12\x1d\n" +
	"\n" +
	"champ_json\x18\x03 \x01(\tR\tchampJson\x12*\n" +
	"\x11profile_icon_json\x18\x04 \x01(\tR\x0fprofileIconJson\x12\"\n" +
	"\rmap_icon_json\x18\x05 \x01(\tR\vmapIconJson\x1a\xd7\v\n" +
	"\x03LCU\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12#\n" +
	"\rgameflow_path\x18\x02 \x01(\tR\fgameflowPath\x122\n" +
	"\x15gameflow_session_path\x18\x03 \x01(\tR\x13gameflowSessionPath\x12%\n" +
	"\x0ereconnect_path\x18\x04 \x01(\tR\rreconnectPath\x12#\n" +
	"\rsummoner_path\x18\x05 \x01(\tR\fsummonerPath\x121\n" +
	"\x15summoner_by_name_path\x18\x06 \x01(\tR\x12summonerByNamePath\x12.\n" +
	"\x13summoner_puuid_path\x18\a \x01(\tR\x11summonerPuuidPath\x12-\n" +
	"\x13summoner_by_id_path\x18\b \x01(\tR\x10summonerByIdPath\x122\n" +
	"\x15summoner_profile_path\x18\t \x01(\tR\x13summonerProfilePath\x12,\n" +
	"\x12summoner_icon_path\x18\n" +
	" \x01(\tR\x10summonerIconPath\x12*\n" +
	"\x11ranked_stats_path\x18\v \x01(\tR\x0frankedStatsPath\x12)\n" +
	"\x10matchmaking_path\x18\f \x01(\tR\x0fmatchmakingPath\x12(\n" +
	"\x10ready_check_path\x18\r \x01(\tR\x0ereadyCheckPath\x129\n" +
	"\x19champ_select_session_path\x18\x0e \x01(\tR\x16champSelectSessionPath\x129\n" +
	"\x19champ_select_actions_path\x18\x0f \x01(\tR\x16champSelectActionsPath\x127\n" +
	"\x18champ_select_trades_path\x18\x10 \x01(\tR\x15champSelectTradesPath\x125\n" +
	"\x17champ_select_swaps_path\x18\x11 \x01(\tR\x14champSelectSwapsPath\x12>\n" +
	"\x1cchamp_select_bench_swap_path\x18\x12 \x01(\tR\x18champSelectBenchSwapPath\x12B\n" +
	"\x1echamp_select_my_selection_path\x18\x13 \x01(\tR\x1achampSelectMySelectionPath\x12D\n" +
	"\x1fchamp_select_skin_carousel_path\x18\x14 \x01(\tR\x1bchampSelectSkinCarouselPath\x122\n" +
	"\x15current_champion_path\x18\x15 \x01(\tR\x13currentChampionPath\x125\n" +
	"\x17perks_current_page_path\x18\x16 \x01(\tR\x14perksCurrentPagePath\x12(\n" +
	"\x10perks_pages_path\x18\x17 \x01(\tR\x0eperksPagesPath\x12,\n" +
	"\x12match_history_path\x18\x18 \x01(\tR\x10matchHistoryPath\x12(\n" +
	"\x10game_detail_path\x18\x19 \x01(\tR\x0egameDetailPath\x12 \n" +
	"\fchat_me_path\x18\x1a \x01(\tR\n" +
	"chatMePath\x12!\n" +
	"\fregalia_path\x18\x1b \x01(\tR\vregaliaPath\x12>\n" +
	"\x1bchallenges_preferences_path\x18\x1c \x01(\tR\x19challengesPreferencesPath\x12\x1d\n" +
	"\n" +
	"lobby_path\x18\x1d \x01(\tR\tlobbyPath\x120\n" +
	"\x14spectate_launch_path\x18\x1e \x01(\tR\x12spectateLaunchPath\x12(\n" +
	"\x10install_dir_path\x18\x1f \x01(\tR\x0einstallDirPathB5Z3github.com/B022MC/soraka-backend/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Global)(nil),              // 3: kratos.api.Global
	(*Server_HTTP)(nil),         // 4: kratos.api.Server.HTTP
	(*Data_Database)(nil),       // 5: kratos.api.Data.Database
	(*Global_ProxyJsonUrl)(nil), // 6: kratos.api.Global.ProxyJsonUrl
	(*Global_LCU)(nil),          // 7: kratos.api.Global.LCU
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2, // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3, // 2: kratos.api.Bootstrap.global:type_name -> kratos.api.Global
	4, // 3: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	5, // 4: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	6, // 5: kratos.api.Global.proxyJsonUrl:type_name -> kratos.api.Global.ProxyJsonUrl
	7, // 6: kratos.api.Global.lcu:type_name -> kratos.api.Global.LCU
	8, // 7: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
