// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Global        *Global                `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetGlobal() *Global {
	if x != nil {
		return x.Global
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type Global struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyUrl      string                 `protobuf:"bytes,1,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
	ProxyJsonUrl  *Global_ProxyJsonUrl   `protobuf:"bytes,2,opt,name=proxyJsonUrl,proto3" json:"proxyJsonUrl,omitempty"`
	Lcu           *Global_LCU            `protobuf:"bytes,3,opt,name=lcu,proto3" json:"lcu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global) Reset() {
	*x = Global{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Global) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *Global) GetProxyJsonUrl() *Global_ProxyJsonUrl {
	if x != nil {
		return x.ProxyJsonUrl
	}
	return nil
}

func (x *Global) GetLcu() *Global_LCU {
	if x != nil {
		return x.Lcu
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Global_ProxyJsonUrl struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemJson        string                 `protobuf:"bytes,1,opt,name=item_json,json=itemJson,proto3" json:"item_json,omitempty"`
	SpellJson       string                 `protobuf:"bytes,2,opt,name=spell_json,json=spellJson,proto3" json:"spell_json,omitempty"`
	ChampJson       string                 `protobuf:"bytes,3,opt,name=champ_json,json=champJson,proto3" json:"champ_json,omitempty"`
	ProfileIconJson string                 `protobuf:"bytes,4,opt,name=profile_icon_json,json=profileIconJson,proto3" json:"profile_icon_json,omitempty"`
	MapIconJson     string                 `protobuf:"bytes,5,opt,name=map_icon_json,json=mapIconJson,proto3" json:"map_icon_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Global_ProxyJsonUrl) Reset() {
	*x = Global_ProxyJsonUrl{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_ProxyJsonUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_ProxyJsonUrl) ProtoMessage() {}

func (x *Global_ProxyJsonUrl) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_ProxyJsonUrl.ProtoReflect.Descriptor instead.
func (*Global_ProxyJsonUrl) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Global_ProxyJsonUrl) GetItemJson() string {
	if x != nil {
		return x.ItemJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetSpellJson() string {
	if x != nil {
		return x.SpellJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetChampJson() string {
	if x != nil {
		return x.ChampJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetProfileIconJson() string {
	if x != nil {
		return x.ProfileIconJson
	}
	return ""
}

func (x *Global_ProxyJsonUrl) GetMapIconJson() string {
	if x != nil {
		return x.MapIconJson
	}
	return ""
}

type Global_LCU struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl            string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	GameflowPath       string                 `protobuf:"bytes,2,opt,name=gameflow_path,json=gameflowPath,proto3" json:"gameflow_path,omitempty"`
	SummonerPath       string                 `protobuf:"bytes,3,opt,name=summoner_path,json=summonerPath,proto3" json:"summoner_path,omitempty"`
	SummonerByNamePath string                 `protobuf:"bytes,4,opt,name=summoner_by_name_path,json=summonerByNamePath,proto3" json:"summoner_by_name_path,omitempty"`
	SummonerPuuidPath  string                 `protobuf:"bytes,5,opt,name=summoner_puuid_path,json=summonerPuuidPath,proto3" json:"summoner_puuid_path,omitempty"`
	RankedStatsPath    string                 `protobuf:"bytes,6,opt,name=ranked_stats_path,json=rankedStatsPath,proto3" json:"ranked_stats_path,omitempty"`
	MatchmakingPath    string                 `protobuf:"bytes,7,opt,name=matchmaking_path,json=matchmakingPath,proto3" json:"matchmaking_path,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Global_LCU) Reset() {
	*x = Global_LCU{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_LCU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_LCU) ProtoMessage() {}

func (x *Global_LCU) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_LCU.ProtoReflect.Descriptor instead.
func (*Global_LCU) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Global_LCU) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Global_LCU) GetGameflowPath() string {
	if x != nil {
		return x.GameflowPath
	}
	return ""
}

func (x *Global_LCU) GetSummonerPath() string {
	if x != nil {
		return x.SummonerPath
	}
	return ""
}

func (x *Global_LCU) GetSummonerByNamePath() string {
	if x != nil {
		return x.SummonerByNamePath
	}
	return ""
}

func (x *Global_LCU) GetSummonerPuuidPath() string {
	if x != nil {
		return x.SummonerPuuidPath
	}
	return ""
}

func (x *Global_LCU) GetRankedStatsPath() string {
	if x != nil {
		return x.RankedStatsPath
	}
	return ""
}

func (x *Global_LCU) GetMatchmakingPath() string {
	if x != nil {
		return x.MatchmakingPath
	}
	return ""
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\x89\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12*\n" +
	"\x06global\x18\x03 \x01(\v2\x12.kratos.api.GlobalR\x06global\"\xa0\x01\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x8f\x01\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x1aP\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"\xf6\x04\n" +
	"\x06Global\x12\x1a\n" +
	"\bproxyUrl\x18\x01 \x01(\tR\bproxyUrl\x12C\n" +
	"\fproxyJsonUrl\x18\x02 \x01(\v2\x1f.kratos.api.Global.ProxyJsonUrlR\fproxyJsonUrl\x12(\n" +
	"\x03lcu\x18\x03 \x01(\v2\x16.kratos.api.Global.LCUR\x03lcu\x1a\xb9\x01\n" +
	"\fProxyJsonUrl\x12\x1b\n" +
	"\titem_json\x18\x01 \x01(\tR\bitemJson\x12\x1d\n" +
	"\n" +
	"spell_json\x18\x02 \x01(\tR\tspellJson\x12\x1d\n" +
	"\n" +
	"champ_json\x18\x03 \x01(\tR\tchampJson\x12*\n" +
	"\x11profile_icon_json\x18\x04 \x01(\tR\x0fprofileIconJson\x12\"\n" +
	"\rmap_icon_json\x18\x05 \x01(\tR\vmapIconJson\x1a\xa4\x02\n" +
	"\x03LCU\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12#\n" +
	"\rgameflow_path\x18\x02 \x01(\tR\fgameflowPath\x12#\n" +
	"\rsummoner_path\x18\x03 \x01(\tR\fsummonerPath\x121\n" +
	"\x15summoner_by_name_path\x18\x04 \x01(\tR\x12summonerByNamePath\x12.\n" +
	"\x13summoner_puuid_path\x18\x05 \x01(\tR\x11summonerPuuidPath\x12*\n" +
	"\x11ranked_stats_path\x18\x06 \x01(\tR\x0frankedStatsPath\x12)\n" +
	"\x10matchmaking_path\x18\a \x01(\tR\x0fmatchmakingPathB5Z3github.com/B022MC/soraka-backend/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Global)(nil),              // 3: kratos.api.Global
	(*Server_HTTP)(nil),         // 4: kratos.api.Server.HTTP
	(*Data_Database)(nil),       // 5: kratos.api.Data.Database
	(*Global_ProxyJsonUrl)(nil), // 6: kratos.api.Global.ProxyJsonUrl
	(*Global_LCU)(nil),          // 7: kratos.api.Global.LCU
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1, // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2, // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3, // 2: kratos.api.Bootstrap.global:type_name -> kratos.api.Global
	4, // 3: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	5, // 4: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	6, // 5: kratos.api.Global.proxyJsonUrl:type_name -> kratos.api.Global.ProxyJsonUrl
	7, // 6: kratos.api.Global.lcu:type_name -> kratos.api.Global.LCU
	8, // 7: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
