// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	current_summoner2 "github.com/B022MC/soraka-backend/internal/biz/current_summoner"
	gamePhaseBiz "github.com/B022MC/soraka-backend/internal/biz/game_phase"
	"github.com/B022MC/soraka-backend/internal/conf"
	currentSummonerRepo "github.com/B022MC/soraka-backend/internal/dal/repo/current_summoner"
	gamePhaseRepo "github.com/B022MC/soraka-backend/internal/dal/repo/game_phase"
	"github.com/B022MC/soraka-backend/internal/infra"
	"github.com/B022MC/soraka-backend/internal/router"
	"github.com/B022MC/soraka-backend/internal/server"
	"github.com/B022MC/soraka-backend/internal/service/lcu"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(global *conf.Global, confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := infra.NewSQLite(data, logger)
	if err != nil {
		return nil, nil, err
	}
	client := infra.NewLCUClient(logger, global)
	infraData, cleanup2, err := infra.NewData(data, db, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	currentSummonerRepository := currentSummonerRepo.NewCurrentSummonerRepo(infraData, logger)
	gamePhaseRepository := gamePhaseRepo.NewGamePhaseRepo(infraData, logger)
	currentSummonerUseCase := current_summoner2.NewCurrentSummonerUseCase(currentSummonerRepository, logger)
	gamePhaseUseCase := gamePhaseBiz.NewGamePhaseUseCase(gamePhaseRepository, logger)
	currentSummonerService := lcu.NewCurrentSummonerService(currentSummonerUseCase)
	gamePhaseService := lcu.NewGamePhaseService(gamePhaseUseCase)
	lcuRouter := router.NewLcuRouter(currentSummonerService, gamePhaseService)
	rootRouter := router.NewRootRouter(lcuRouter)
	ginServer := server.NewHTTPServer(confServer, logger, rootRouter)
	app := newApp(logger, ginServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
